### ISSUE TITLE
Ubuntu Client won't install

### ISSUE THREAD

**Issue by tmccal2** [prey/prey-bash-client#416]
I'm on Ubuntu 14.04 release, and I can't get Prey to install. When I tried to, I get the message that it can't install scrot:i386.

**Comment by ndrwprk** [comment]
if i'm not mistaken, unless your machine is 32-bit, the prey_1.4.2_i386.deb package won't work. try the prey_1.4.2_amd64-1.deb package (assuming you're using a 64-bit machine)
