### ISSUE TITLE
Conflict with Little Snitch?

### ISSUE THREAD

**Issue by Jmuccigr** [prey/prey-bash-client#417]
With Little Snitch on, I don't see any rules that obviously block Prey, but I'm getting only "device reached" with my laptop. No location info, messages or alarms are getting through. Turning off Little Snitch eliminates the problem.

**Comment by ozxmin** [comment]
I have the same problem. Have you find a solution other than turning off little snitch?

**Comment by emabartolomucci** [comment]
Same here, as soon as I disable the Network Filter for other things, I immediately get the email "**[Prey] Device xyz is back online**!", even if I'm sure there's no active rule preventing node from connecting to the internet.

**Comment by moltar** [comment]
+1

**Comment by seabasss** [comment]
+1

**Comment by yashendra2797** [comment]
+1

**Comment by emabartolomucci** [comment]
After more than one and a half year, there's still no reply from the developers?

**Comment by fanuneza** [comment]
Hi guys,

This client is no longer supported. It was deprecated in favor of https://github.com/prey/prey-node-client
