### ISSUE TITLE
current prey-bash-client status and possible alternatives

### ISSUE THREAD

**Issue by baimafeima** [prey/prey-bash-client#421]
This project looks unmaintained. Please advise whether this project is:

- still maintained and release an updated version
- is unmaintained and mark this project as abandoned due to lack of a maintainer
- abandoned due to a better alternative

A recent request to add Prey to the Solus repositories was declined because it doesn't make sense to land unmaintained software in the repositories: https://dev.solus-project.com/T1688

Your feedback is greatly appreciated.

OS: Solus (https://solus-project.com/)

**Comment by yakatz** [comment]
Prey now uses a nodejs client: https://github.com/prey/prey-node-client
The Bash client has not been used in a long time.
