### ISSUE TITLE
Problem with sound

### ISSUE THREAD

**Issue by AlejoMedina98** [prey/prey-bash-client#422]
If I send an alarm to the device, people can decrease the volume, there are any method to avoid this?

**Comment by yakatz** [comment]
If you are using the Bash client, likely not, but it can depend on what operating system you are using.
You might also be able to find a program that can raise the volume before it plays a sound.
The place to add it would be this module: https://github.com/prey/prey-bash-client-modules/tree/master/alarm in the folder specific to your platform.

If you are using the Node.js client (the modern version), this may already be included: https://github.com/prey/prey-node-client/blob/55d383125eb6c62c4627017f7c560625da16e232/lib/agent/actions/alarm/index.js#L38
