### ISSUE TITLE
Wrong location on Prey 1.7.1

### ISSUE THREAD

**Issue by Julianinho** [prey/prey-bash-client#424]
Hi,

I have a wrong location (10km) on my laptop with thne last Prey 1.7.1.
I use the wifi on my laptop windows, i have test my location on google maps and google find the good location, so there is a problem with Prey i think.

I have reinstal Prey, i will tested the version 64bits and the 32 bits but nothing, i have the same problem with an another laptop dell on windows.

Have you any idea ?
Thanks
Best regard

**Comment by javo** [comment]
Hi @Julianinho, can I see your C:\Windows\Prey\prey.log file? so I can detect the problem

Javo

**Comment by Julianinho** [comment]
Hi @javo ,
Tanks for help, this is my log file : 

`  PREY 1.7.1 spreads its wings!
  Current time: Wed Sep 20 2017 21:24:46 GMT+0200 (Paris, Madrid (heure d’été))
  Running with PID 10108 as JULIANINHO_PC_ over Node.js v4.4.5 on a x64 windows system (undefined)

     warn Wed, 20 Sep 2017 19:24:46 GMT [control-panel] Not configured. Waiting for user input...
     info Wed, 20 Sep 2017 19:24:56 GMT [control-panel] Reloading config...
     info Wed, 20 Sep 2017 19:25:06 GMT [control-panel] Reloading config...
     info Wed, 20 Sep 2017 19:25:16 GMT [control-panel] Reloading config...
     info Wed, 20 Sep 2017 19:25:16 GMT Plugin loaded: control-panel
     info Wed, 20 Sep 2017 19:25:16 GMT 1 plugins loaded with 0 errors.
     info Wed, 20 Sep 2017 19:25:16 GMT Initialized.
     info Wed, 20 Sep 2017 19:25:16 GMT [triggers] Watching: connection, control-zones, location, network, power
     info Wed, 20 Sep 2017 19:25:16 GMT [actions] Starting trigger: connection
     info Wed, 20 Sep 2017 19:25:16 GMT [actions] Running: connection
     info Wed, 20 Sep 2017 19:25:16 GMT [actions] Starting trigger: control-zones
     info Wed, 20 Sep 2017 19:25:16 GMT [actions] Running: control-zones
     info Wed, 20 Sep 2017 19:25:16 GMT [actions] Starting trigger: location
     info Wed, 20 Sep 2017 19:25:16 GMT [actions] Running: location
     info Wed, 20 Sep 2017 19:25:16 GMT [actions] Starting trigger: network
     info Wed, 20 Sep 2017 19:25:16 GMT [actions] Starting trigger: power
     info Wed, 20 Sep 2017 19:25:16 GMT [actions] Running: network
     info Wed, 20 Sep 2017 19:25:16 GMT [actions] Running: power
   notice Wed, 20 Sep 2017 19:25:17 GMT [control-panel] Updating value of auto_connect to true
     info Wed, 20 Sep 2017 19:25:45 GMT [long-polling] Got 1 commands.
     info Wed, 20 Sep 2017 19:27:14 GMT [long-polling] Got 1 commands.
     info Wed, 20 Sep 2017 19:27:25 GMT [long-polling] Got 1 commands.`

**Comment by javo** [comment]
That's all of it? Can you go to the control panel and ask for the location again.. then attach the file instead of pasting it?

**Comment by Julianinho** [comment]
Hi @javo ,

I have attach the file and i have a message on the control panel when i ask location : unable to have location, waiting to location... and unable...

Thanks.
[prey.zip](https://github.com/prey/prey-bash-client/files/1321722/prey.zip)

**Comment by javo** [comment]
Hey @Julianinho,
I can see that your device is having troubles connecting to the control panel, you can try deactivating firewalls or the antivirus if you have any. 
If that doesn't work try connecting using another wifi network, you can use an access point from your phone.
Let me know how it goes :)

**Comment by Julianinho** [comment]
Hi @javo ,

I will try with eset antivirus and firewall disable with firefox, chrome, edge and with access point from my phone and same problem :(
[prey.zip](https://github.com/prey/prey-bash-client/files/1322460/prey.zip)

**Comment by javo** [comment]
On your browser go to https://solid.preyproject.com/test, It's a connectivity test to Prey. Is there anything in red?

**Comment by Julianinho** [comment]
Hi @javo ,

Yes, all is ok on the link, i have the 5 lines in green.

**Comment by javo** [comment]
Hi @Julianinho, can I have you email so I can send you an installation package that might solve the problem. I can't send it through here :(

**Comment by Julianinho** [comment]
Hi @javo 
Thanks for help.
I will send my email on mp.

**Comment by ok-web** [comment]
Hi @javo ,

I got the same issue w/ version 1.7.2x86 for windows here. Switching off ms positioning doesn't help while google maps works fine at the same time. Do you have any suggestions or help for me?

BTW: The connectivity test works fine as well.

Thx,
Olaf

**Comment by javo** [comment]
Hey @ok-web,
In order to get the location prey uses the nearest wi-fi networks info. It seems there's some cases on windows when the data obtained is only the network you're connected on, so the location can't be correctly estimated.
I've been working on it and it's gonna be fixed for the 1.7.3 version very soon (next monday tops). However it'd be really useful if you can try it before that so I can be totally sure that the problem is solved. If you wanna try it you can give me an email address and i'd send you an installer package :)

Thank you and sorry for the troubles.
Regards,
Javo

**Comment by ok-web** [comment]
Hi @javo,

that sounds good! I can test the new version. Pls. send it to evh51@hotmail.com. I'll send you feedback by tomorrow latest.

Regards,
Olaf

**Comment by javo** [comment]
Hey, the new client version 1.7.3 it's now available, please check you have that version installed and try locating your device again, should work fine now. Please let me know how it's working.
